---
apiVersion: v1
data:
  patch-resolve.conf.sh: |-
      #!/bin/bash
      set +x

      MOD_LINE="# $(date -u) - modified by resolve-host-patcher on boot"

      grep -v 'resolve-host-patcher' /var/run/host-etc/resolv.conf > /tmp/original-node-resolve.conf

      echo "${MOD_LINE}" > /tmp/kube-resolv.conf
      for ip in $(grep ^nameserver /etc/resolv.conf | awk '{$1=""; print}'); do
        echo "nameserver ${ip} # added by resolve-host-patcher" >> /tmp/kube-resolv.conf
      done

      cat /tmp/kube-resolv.conf /tmp/original-node-resolve.conf | sed '/^$/d'  > /var/run/host-etc/resolv.conf
kind: ConfigMap
metadata:
  name: scripts-resolve-host-patcher
  namespace: kube-system

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: resolve-host-patcher
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: resolve-host-patcher
  template:
    metadata:
      labels:
        name: resolve-host-patcher
    spec:
      containers:
      - image: bash
        name: resolve-host-patcher
    
        command: ["bash"]
        args: [ "/patch-resolve.conf.sh" ]
    
        volumeMounts:
        - mountPath: /var/run/host-etc/
          name: etc
        - mountPath: /patch-resolve.conf.sh
          name: config
          subPath: patch-resolve.conf.sh

      volumes:
      - name: etc
        hostPath:
          path: /etc
      - name: config
        configMap:
          defaultMode: 420
          name: scripts-resolve-host-patcher
